name: Test Bindings
on: [push]

jobs:
  linux-x86_64:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
        with:
          just-version: '1.51.0'
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: dev-2026-05
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libgtk-4-dev libadwaita-1-dev
          version: 2

      - name: check
        run: |
          just check glib/gio '' \
               check glib/girepository '' \
               check glib/gmodule '' \
               check glib/gobject '' \
               check glib '' \
               check cairo '' \
               check gdk-pixbuf '' \
               check graphene '' \
               check pango '' \
               check pango/pangocairo '' \
               check helper '' \
               check gtk '' \
               check gtk/layer-shell '' \
               check adwaita ''

      - name: examples
        run: |
          just example gtk-snake '' \
               example hello-cairo '' \
               example hello-gdk-pixbuf '' \
               example hello-gio '' \
               example hello-glib '' \
               example hello-gmodule '' \
               example hello-gobject '' \
               example hello-gtk '' \
               example hello-pango '' \
               example widget-template-manual '' \
               example widget-template-with-helper ''

      - name: test examples
        run: |
          build/hello-glib
          build/hello-gmodule
          build/hello-gobject
          build/hello-gio build
          build/hello-pango
          build/hello-gdk-pixbuf build/pango_output.png build/pango_output_scaled.png 2
          build/hello-cairo


  linux-aarch64:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
        with:
          just-version: '1.51.0'
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: dev-2026-05
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libgtk-4-dev libadwaita-1-dev
          version: 2

      - name: check
        run: |
          just check glib/gio '' \
               check glib/girepository '' \
               check glib/gmodule '' \
               check glib/gobject '' \
               check glib '' \
               check cairo '' \
               check gdk-pixbuf '' \
               check graphene '' \
               check pango '' \
               check pango/pangocairo '' \
               check helper '' \
               check gtk '' \
               check gtk/layer-shell '' \
               check adwaita ''

      - name: examples
        run: |
          just example gtk-snake '' \
               example hello-cairo '' \
               example hello-gdk-pixbuf '' \
               example hello-gio '' \
               example hello-glib '' \
               example hello-gmodule '' \
               example hello-gobject '' \
               example hello-gtk '' \
               example hello-pango '' \
               example widget-template-manual '' \
               example widget-template-with-helper ''

      - name: test examples
        run: |
          build/hello-glib
          build/hello-gmodule
          build/hello-gobject
          build/hello-gio build
          build/hello-pango
          build/hello-gdk-pixbuf build/pango_output.png build/pango_output_scaled.png 2
          build/hello-cairo


  windows-x86_64:
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
        with:
          just-version: '1.51.0'
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: dev-2026-05
      - uses: ilammy/msvc-dev-cmd@v1

      - name: create windows runtime cache key
        id: windows-runtime-cache-key
        run: |
           $output_entry = "key=windows-runtime-" + (just windows-gvsbuild-version)
           echo $output_entry >> $env:GITHUB_OUTPUT
      - name: cache windows runtime
        id: cache-windows-runtime
        uses: actions/cache@v5
        with:
          key: ${{ steps.windows-runtime-cache-key.outputs.key }}
          path: |
            build/*.dll
            build/share
            build/etc
      - name: install windows runtime
        if: steps.cache-windows-runtime.outputs.cache-hit != 'true'
        run: just install-windows-runtime 'build'

      - name: check
        run: |
          just check glib/gio '' `
               check glib/girepository '' `
               check glib/gmodule '' `
               check glib/gobject '' `
               check glib '' `
               check cairo '' `
               check gdk-pixbuf '' `
               check graphene '' `
               check pango '' `
               check pango/pangocairo '' `
               check helper '' `
               check gtk '' `
               check gtk/layer-shell '' `
               check adwaita ''

      - name: examples
        run: |
          just example gtk-snake '' `
               example hello-adwaita '' `
               example hello-cairo '' `
               example hello-gdk-pixbuf '' `
               example hello-gio '' `
               example hello-glib '' `
               example hello-gmodule '' `
               example hello-gobject '' `
               example hello-gtk '' `
               example hello-pango '' `
               example widget-template-manual '' `
               example widget-template-with-helper ''

      - name: test examples
        run: |
          build/hello-glib
          build/hello-gmodule
          build/hello-gobject
          build/hello-gio build
          build/hello-pango
          build/hello-gdk-pixbuf build/pango_output.png build/pango_output_scaled.png 2
          build/hello-cairo
